know={
    "PLEASE SPEAK ENGLISH TO ME": [
        "WHAT DO YOU MEAN?",
        "ARE YOU SAYING THAT I'M NOT SPEAKING ENGLISH TO YOU?"
    ],
    "WHAT ELSE": [
        "WELL,I DON'T KNOW.",
        "WHAT ELSE SHOULD THERE BE?",
        "THIS LOOKS LIKE A COMPLICATED QUESTION TO ME."
    ],
    "A COMPUTER CAN": [
        "DO YOU LIKE COMPUTERS?",
        "I LIVE INSIDE A COMPUTER.",
        "WITHOUT COMPUTERS A LOT OF THINGS WOULDN'T BE POSSIBLE TODAY?"
    ],
    "ARE YOU INTELLIGENT": [
        "YES,OF COURSE.",
        "WHAT DO YOU THINK?",
        "ACTUALY,I'M VERY INTELLIGENT!"
    ],
    "I HATE YOU": [
        "WHAT IS IT THAT YOU HATE?"
    ],
    "CAN YOU SPEAK FRENCH": [
        "NO I CAN'T.",
        "PERHAPS I CN LEARN TOO.",
        "RIGHT NOT I DON'T SPEAK FRENCH, MAYBE IN THE FUTURE I WILL."
    ]
}